### ISSUE TITLE
Documentação Componentes

### ISSUE THREAD

**Issue by Chandee** [Portal-da-Classe-Politica/portal-da-classe-politica#2]
Mapeamento componentes
***
 CustomButton  
- [x] Doing
- [x] Done
 ![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/d4c8a6ae-787d-48e5-8e84-4bcd29f5379b) </p>
***
BoxFerramenta
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/1ad1d38c-3f4b-49de-a7d6-56635144a991)
***
BoxAnalise 
 - [x] Doing
 - [x] Done
- Primario
 ![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/1ed388a5-85e1-4fc0-b7a2-9a8edd2dc0c1) 
- Secundario
 ![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/b6446dfc-c97c-4549-8d43-9ac10ab00a3c) 
- Terciario 
 ![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/90a7767b-1b22-4793-b9e7-b71e758c7553)
***
BoxData 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/b162c4cc-2c73-4918-ab1a-2c0329ae0fd3)<br>![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/ed1135fd-ad50-474d-af72-ec4eb6672c17)
***
SelectTab
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/fa188b7e-a6ea-487f-913f-eaf584233d5c)
***
 BoxIconText
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/afaed263-ec1c-45be-95d9-791f64a8d263)
***
LogoIcon
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/4482da2a-51c6-4f20-824a-a558fec1e0e3)
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/2f4f4540-b6f6-4822-aaa2-60b0fe62f0c8)
***
TextIcon
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/3550aa26-f026-4142-a497-646d80c366ba)
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/e6863790-8fee-4440-bf34-adf2257056d8)
Icone podendo ser esquerda ou direita 
***
BoxIcon 
- [x] Doing
- [x] Done
 ![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/a307477f-70fb-434f-a132-8ab0652ab93f)
***
ButtonSelect
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/ab72a14f-7347-43aa-8192-4e08a1599084) 
***
ButtonSelectIcon ( ou criar variante do ButtonSelect)
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/2890900b-6173-43f1-891d-85ff1863f5fa) 
***
DateSelector 
- [x] Doing
- [x] Done 
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/e4c1870a-12c3-4fab-9d21-31ca82ecf55a)
***
 BulletList 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/eb0eeb50-de4c-462a-b42d-7d63649c7bb3)
***
 BoxContainer 
- [x] Doing
- [x] Done 
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/3bea43c7-7b24-48e3-9509-a3be5b1b2760) 
***
ChipContainer 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/d9bbf8e6-8fb3-4bb2-8e30-d3e7e84a1280) 
***
TextInput 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/6e5e8290-f8fb-40e7-9ea4-ecf353c36850) 
***
Avatar 
- [x] Doing
- [x] Done
- Left 
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/ab39ca21-32bf-4e54-b79a-367e5911431a) 
- Up 
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/1abcd59c-ab59-4f24-9f6e-bff27d26ca54)
***
 TimeLine 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/1b13ad49-b407-440b-8313-71292bd1338b) 
***
TimeLineBox 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/7db1d63b-02fa-442f-a11c-bd0398a398ae)  
***
LineList 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/a29114e1-53bb-4413-9ced-6bf4604e42a3) 
***
Table 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/affbb2c3-0b02-4342-ab2e-47b3cf158ef5)
***
PerfilCandidateSmall 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/bcd6c795-20a3-48b3-a3de-5eb5c69b144e) 
***
 PerfilCandidate
 - [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/0d1942ca-86f1-440d-bc7d-f2884779bdaf)
***
 CandidateInfo 
 - [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/0a60c11a-8aa9-4b3f-87a3-fecbac9f7eb4)
***
CandidateResult
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/1db5c3e8-8238-4256-957d-cbbe1215aa29)
***
CandidateFinantials 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/01e543be-e71a-4c80-8ffc-e2e171644946)
***
ArrowList 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/74366b55-927e-4f19-977b-125de329fd93)
***
Header 
- [x] Doing
- [x] Done
![image](https://github.com/Portal-da-Classe-Politica/portal-da-classse-politica/assets/28514068/333f1caa-ecaf-411e-98dc-9857825c8fe4)

**Comment by Chandee** [comment]
- [ ] asdasda
- [ ] asdasdas
- [ ] asdasd

**Comment by LFabre** [comment]
Completed Button Component

**Comment by LFabre** [comment]
Completed Box Data
